name: Update Common Config
on: [push]
jobs:
  update-common-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull in subtree
        uses: xanjohns/common-config-action@v5.0.1
