name: Update Common Config
on:
  schedule:
    - cron: '13 2 * * *'
jobs:
  update-common-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
         
